const UK_STORES_AND_SERVICES = [
  { id: 1, name: "Tesco" },
  { id: 2, name: "Sainsbury's" },
  { id: 3, name: "Asda" },
  { id: 4, name: "Morrisons" },
  { id: 5, name: "Aldi" },
  { id: 6, name: "Lidl" },
  { id: 7, name: "Waitrose" },
  { id: 8, name: "Marks & Spencer" },
  { id: 9, name: "Co-op Food" },
  { id: 10, name: "Iceland" },
  { id: 11, name: "Boots" },
  { id: 12, name: "Superdrug" },
  { id: 13, name: "WHSmith" },
  { id: 14, name: "John Lewis & Partners" },
  { id: 15, name: "Debenhams" },
  { id: 16, name: "House of Fraser" },
  { id: 17, name: "Primark" },
  { id: 18, name: "Next" },
  { id: 19, name: "River Island" },
  { id: 20, name: "Topshop" },
  { id: 21, name: "H&M" },
  { id: 22, name: "Zara" },
  { id: 23, name: "New Look" },
  { id: 24, name: "Matalan" },
  { id: 25, name: "Sports Direct" },
  { id: 26, name: "JD Sports" },
  { id: 27, name: "Argos" },
  { id: 28, name: "B&Q" },
  { id: 29, name: "Homebase" },
  { id: 30, name: "Wickes" },
  { id: 31, name: "Screwfix" },
  { id: 32, name: "Currys" },
  { id: 33, name: "PC World" },
  { id: 34, name: "Carphone Warehouse" },
  { id: 35, name: "O2" },
  { id: 36, name: "EE" },
  { id: 37, name: "Vodafone" },
  { id: 38, name: "Three" },
  { id: 39, name: "Greggs" },
  { id: 40, name: "Costa Coffee" },
  { id: 41, name: "Caffè Nero" },
  { id: 42, name: "Pret A Manger" },
  { id: 43, name: "Starbucks" },
  { id: 44, name: "PizzaExpress" },
  { id: 45, name: "Nando's" },
  { id: 46, name: "Wagamama" },
  { id: 47, name: "KFC" },
  { id: 48, name: "McDonald's" },
  { id: 49, name: "Burger King" },
  { id: 50, name: "Subway" },
  { id: 51, name: "Domino's Pizza" },
  { id: 52, name: "Pizza Hut" },
  { id: 53, name: "Five Guys" },
  { id: 54, name: "Wetherspoons" },
  { id: 55, name: "Harvester" },
  { id: 56, name: "Toby Carvery" },
  { id: 57, name: "Beefeater" },
  { id: 58, name: "Premier Inn" },
  { id: 59, name: "Travelodge" },
  { id: 60, name: "Holiday Inn" },
  { id: 61, name: "Hilton Hotels" },
  { id: 62, name: "Marriott Hotels" },
  { id: 63, name: "Radisson Blu" },
  { id: 64, name: "Ibis Hotels" },
  { id: 65, name: "Novotel" },
  { id: 66, name: "Mercure Hotels" },
  { id: 67, name: "Lloyds Bank" },
  { id: 68, name: "Barclays" },
  { id: 69, name: "HSBC" },
  { id: 70, name: "NatWest" },
  { id: 71, name: "Santander" },
  { id: 72, name: "Halifax" },
  { id: 73, name: "Nationwide Building Society" },
  { id: 74, name: "TSB Bank" },
  { id: 75, name: "Royal Bank of Scotland" },
  { id: 76, name: "Metro Bank" },
  { id: 77, name: "Post Office" },
  { id: 78, name: "DHL" },
  { id: 79, name: "UPS" },
  { id: 80, name: "FedEx" },
  { id: 81, name: "Hermes" },
  { id: 82, name: "DPD" },
  { id: 83, name: "Yodel" },
  { id: 84, name: "Royal Mail" },
  { id: 85, name: "Specsavers" },
  { id: 86, name: "Vision Express" },
  { id: 87, name: "Timpson" },
  { id: 88, name: "Max Spielmann" },
  { id: 89, name: "Clarks" },
  { id: 90, name: "Schuh" },
  { id: 91, name: "The Body Shop" },
  { id: 92, name: "Holland & Barrett" },
  { id: 93, name: "Lush" },
  { id: 94, name: "Paperchase" },
  { id: 95, name: "Waterstones" },
  { id: 96, name: "WHSmith Travel" },
  { id: 97, name: "Lakeland" },
  { id: 98, name: "Robert Dyas" },
  { id: 99, name: "Ryman" },
  { id: 100, name: "Maplin" },
];

export default UK_STORES_AND_SERVICES;
